name: shadcn_flutter
description: "Beautifully designed components from Shadcn/UI is now available for Flutter"
version: 0.0.16
homepage: "https://github.com/sunarya-thito/shadcn_flutter"

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  email_validator: ">=2.1.17"
  flutter:
    sdk: flutter
  gap: ">=3.0.1"
  skeletonizer: ">=1.3.0"
  shadcn_flutter_platform_interface: ^0.0.3
  shadcn_flutter_web: ^0.0.2
  shadcn_flutter_independent: ^0.0.3
  syntax_highlight: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icon_font_generator: ^4.0.0
  archive: ^3.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      web:
        default_package: shadcn_flutter_web
      ios:
        default_package: shadcn_flutter_independent
      android:
        default_package: shadcn_flutter_independent
      windows:
        default_package: shadcn_flutter_independent
      linux:
        default_package: shadcn_flutter_independent
      macos:
        default_package: shadcn_flutter_independent

topics:
  - widgets
  - ui
  - design
  - components
  - shadcn-ui

